services:
  - type: web
    name: shopkeeper-website
    runtime: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
